### ISSUE TITLE
Upgrade RocketChat

### ISSUE THREAD

**Issue by azaqero** [AlexTr/Rocket.Chat.Orig#1]
Your Rocket.Chat version: 0.20.0

I installed the rocketchat bundle, this is running version 0.20.0

how can i upgrade to the latest rocket.chat version 0.26.0?

**Comment by AlexTr** [comment]
We update Chat+ with new Dolphin version or some significant changes or serious bugs need to be urgently fixed. So please wait until new Dolphin version.
