### ISSUE TITLE
Change nameIDFormat

### ISSUE THREAD

**Issue by localguru** [AlexTr/Rocket.Chat.Orig#2]
Your Rocket.Chat version: 0.52.0

Hi,

how do I change the nameIDFormat 

```
<NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
```

as I get error "Required NameID format not supported" when testing SAML with Shibboleth, see https://github.com/RocketChat/Rocket.Chat/issues/6317

Thanks
Marcus

**Comment by AlexTr** [comment]
I would suggest to ask it in the original Rocket.Chat repository:
https://github.com/RocketChat/Rocket.Chat/issues
